--- 

- hosts: web
  become: yes 
  tasks: 
  - name: Disable Firewall
    service: name=ufw state=stopped enabled=False




- hosts: web
  name: "Testing Ansible Roles"
  become: yes
  roles:
  - firewall 
